### ISSUE TITLE
Some way to derive locale from a country?

### ISSUE THREAD

**Issue by marr** [koa-modules/locale#4]
This isn't really an issue related to koa-locale, but I am trying to think of a way to leverage this module and am running into a wall. I have an identity provider which will give me a users country.

To determine a users locale, I have 4 country values that are possibilities (US, UK, AU, NZ). Since this doesn't include a locale (en-GB, or en-US for example) -- and my app will live at one URL -- how could I derive a reasonable locale? 

From what I can tell an `Accept-Languages` header of `en,en-US;q=0.8` the default in a US chrome browser, the locale found by `getLocaleFromHeader` is `en`. I'd like to serve up `en-US` translations in that case but I'm not sure how to achieve that. Likewise with an en-GB browser I'd like to serve up the British translations. Is there a flag somewhere to choose the more specific locale given a country?

**Comment by fundon** [comment]
@marr Update to v0.1.2. And use the `getLocaleFromHeader(true)` will return the locals array. 

`en,en-US;q=0.8` => `['en', 'en-US']`
